apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: weaveworks-nginx
spec:
  description: Profile for deploying nginx
  version: v0.1.0
  artifacts:
    - name: nginx-deployment
      path: nginx/deployment
      kind: Kustomize
