apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: nested-nginx-1
spec:
  description: Profile for deploying local nginx chart
  version: v0.0.1
  artifacts:
    - name: nginx-server
      path: nginx/chart
      kind: HelmChart
    - name: nested-nginx-2
      kind: Profile
      profile:
        url: https://github.com/weaveworks/profiles-examples
        version: nested-nginx-2/v0.0.1