apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: branch-nginx
spec:
  description: Profile for deploying nginx on a branch
  version: v0.0.2
  artifacts:
    - name: nginx-deployment
      path: nginx/deployment
      kind: Kustomize